version: '3.8'

services:
  me:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: me
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - me
    command: >
      certbot certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email damarmuhamad13@gmail.com 
      --agree-tos 
      --no-eff-email 
      -d damar-galih.tech